---
title: "faq"
output: html_document
---

### Frequently Asked Questions

**Why I received a message 'Disconnected from server'?** <br/>
By default, an application will close an idle connection after 15 minutes of inactivity. This means if you open an application and do not interact with it for 15 minutes, you will see a disconnect (grey screen).<br/>
**Solution**: refresh the webpage or click the F5 on the keyboard.



### Questions & Problems

If you have any questions or problems when using ICTD, please feel free to open a new issue [here](https://github.com/zy26/ICTD/issues). We will fix the new issue ASAP.  You can also email the maintainers and authors below.

- [Wennan Chang](https://zcslab.github.io/people/wennan/)
(wnchang@iu.edu)

PhD candidate at BDR group, Indiana University School of Medicine

- [Chi Zhang](https://medicine.iu.edu/departments/genetics/faculty/27057/zhang-chi/)
(czhang87@iu.edu)

Assistant Professor

Department of Medical & Molecular Genetics, Indiana University School of Medicine



### Dependencies

We also provide a Docker image to recreate the compute environment. See the Dockerfile for more details.

https://hub.docker.com/r/wnchang/ictd

Using the Docker image could void the conflict issue that R version and several R packages version confict. 

For more details about the Docker, please see Docker documentation page https://docs.docker.com/.


